# Generated by Django 5.0.6 on 2024-07-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamPayReplenishment',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(choices=[(10, 10), (20, 20), (50, 50), (75, 75), (100, 100)], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteamPayReplenishmentCode',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.steampayreplenishment')),
            ],
        ),
    ]
