# Generated by Django 5.0.6 on 2024-07-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('expired', models.CharField(max_length=100)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPaymentPostback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('merchant_id', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('amount_currency', models.CharField(max_length=100)),
                ('profit', models.CharField(max_length=100)),
                ('profit_currency', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=100)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
