# Generated by Django 5.0.6 on 2024-07-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderpayment_orderpaymentpostback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayment',
            old_name='order_id',
            new_name='order',
        ),
    ]
