# Generated by Django 5.0.6 on 2024-07-10 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderpayment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentpostback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
