# Generated by Django 5.0.6 on 2024-07-08 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(choices=[('USD', 'UDS')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('method', models.CharField(max_length=50)),
                ('success_url', models.URLField(blank=True)),
                ('fail_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nicepay.merchants')),
            ],
        ),
    ]
