# Generated by Django 5.0.6 on 2024-07-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicepay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
