# Generated by Django 5.0.6 on 2024-07-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicepay', '0002_payment_is_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_payed',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('wait_pay', 'wait_pay'), ('wait_approve', 'wait_approve'), ('approved', 'approved'), ('not_approved', 'not_approved')], default='wait_pay', max_length=20),
        ),
    ]
