# Generated by Django 5.0.6 on 2024-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicepay', '0003_remove_payment_is_payed_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
