# Generated by Django 5.0.6 on 2024-07-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicepay', '0004_remove_payment_id_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expired',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
